[settings]
experimental = true
vfox = false
idiomatic_version_file_enable_tools = ["ruby"]

[tools]
go = "latest"
lua = "latest"
golangci-lint = "latest"
erlang = "latest"
elixir = "latest"
usage = "latest"
ghcup = "latest"
node = "latest"
watchexec = "latest"
rust = "latest"
uv = "latest"
ruby = "4.0-dev"
